### ISSUE TITLE
Resources: New palettes of Nanning

### ISSUE THREAD

**Issue by NNTR** [railmapgen/rmg-palette#381] opened 2023-01-29 09:02 UTC
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

(REPLACE ME/替代我)
**Reference link:** http://www.nngdjt.com/images/yyfw/line5_lar.png

**Justification:**  南宁轨道交通的线路标志色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "nanning",
    "country": "CN",
    "name": {
        "en": "Nanning",
        "zh-Hans": "南宁",
        "zh-Hant": "南寧"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "nn1",
        "colour": "#62db6b",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "nn2",
        "colour": "#ee3d2d",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "nn3",
        "colour": "#a81ba7",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "nn4",
        "colour": "#cdd718",
        "fg": "#000",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "nn5",
        "colour": "#3a61a8",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "nn6",
        "colour": "#e97c17",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "nn7",
        "colour": "#ac6a4f",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "nn8",
        "colour": "#1fc4c8",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    }
]</details>

**Comment by 52PD** [comment] 2023-01-29 17:53
Duplicate of #378

**Closed by 52PD** 2023-01-29 17:53 UTC
Labels: duplicate, resources
