### ISSUE TITLE
Resources: New palettes of Okayama

### ISSUE THREAD

**Issue by leowulinhui** [railmapgen/rmg-palette#1409] opened 2024-10-10 03:21 UTC
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Data source:** 1. 官方网站发布的设计标准

**Reference link:** https://okayama-kido.co.jp/tram/

**Justification:** 新增地区

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"","country":"JP","name":{"en":"Okayama","zh-Hans":"冈山","zh-Hant":"岡山","ja":"岡山"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"oH1","colour":"#e5330d","fg":"#fff","name":{"en":"Higashiyama Line","zh-Hans":"东山线","ja":"東山線","zh-Hant":"東山線"}},{"id":"oS1","colour":"#3d7f44","fg":"#fff","name":{"en":"Seikibashi Line","zh-Hans":"清辉桥线","ja":"清輝橋線","zh-Hant":"清會橋線"}}]</details>

**Comment by linchen1965** [comment] 2024-10-12 13:31
Closed as duplicate of https://github.com/railmapgen/rmg-palette/issues/1413

**Closed by linchen1965** 2024-10-12 13:31 UTC
Labels: resources
