### ISSUE TITLE
Resources: New palettes of Zhengzhou

### ISSUE THREAD

**Issue by Sure85** [railmapgen/rmg-palette#692] opened 2023-07-18 07:17 UTC
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

(REPLACE ME/替代我)
**Reference link:** http://tieba.baidu.com/p/8382885959?&share=9105&fr=sharewise&is_video=false&unique=742B48DAC9EC639F4ABAF7C6885BCFBB&st=1689664257&client_type=1&client_version=12.43.9.0&sfc=copy&share_from=post&source=12_16_sharecard_a

**Justification:** 郑州地铁发布了新的地铁规划，线路更新需要更改配色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "zhengzhou",
    "country": "CN",
    "name": {
        "en": "Zhengzhou",
        "zh-Hans": "郑州",
        "zh-Hant": "鄭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "zz1",
        "colour": "#d71b18",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "zz2",
        "colour": "#fff100",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "zz3",
        "colour": "#f09939",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "zz4",
        "colour": "#00a0e9",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "zz5",
        "colour": "#0e6935",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "zz6",
        "colour": "#920e80",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "zz7",
        "colour": "#d6a053",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "zz8",
        "colour": "#e3e289",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "zz9",
        "colour": "#a1ae73",
        "fg": "#fff",
        "name": {
            "en": "Suburban Line",
            "zh-Hans": "9号线（城郊线）",
            "zh-Hant": "9號線（城郊線）"
        }
    },
    {
        "id": "zz10",
        "colour": "#be6254",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "zz12",
        "colour": "#1e609f",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "zz14",
        "colour": "#b289bc",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "zzS1",
        "colour": "#1D4155",
        "fg": "#fff",
        "name": {
            "en": "Line S1 (Zhengxu Line)",
            "zh-Hans": "S1号线（郑许线）",
            "zh-Hant": "SI號線（鄭許線）"
        }
    },
    {
        "id": "zz11",
        "colour": "#91aeb2",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "zz13",
        "colour": "#7586b9",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "zz15",
        "colour": "#e591df",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "zz16",
        "colour": "#b87626",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "zz17",
        "colour": "#662d91",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "zz18",
        "colour": "#3cc2b1",
        "fg": "#fff",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "zz19",
        "colour": "#6ed34a",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    },
    {
        "id": "zz20",
        "colour": "#86e1d0",
        "fg": "#fff",
        "name": {
            "en": "Line 20",
            "zh-Hans": "20号线",
            "zh-Hant": "20號線"
        }
    },
    {
        "id": "zz21",
        "colour": "#fe6b00",
        "fg": "#fff",
        "name": {
            "en": "Line 21",
            "zh-Hans": "21号线",
            "zh-Hant": "21號線"
        }
    },
    {
        "id": "zz22",
        "colour": "#1d9add",
        "fg": "#fff",
        "name": {
            "en": "Line 22",
            "zh-Hans": "22号线",
            "zh-Hant": "22號線"
        }
    },
    {
        "id": "zz23",
        "colour": "#308f40",
        "fg": "#fff",
        "name": {
            "en": "Line 23",
            "zh-Hans": "23号线",
            "zh-Hant": "23號線"
        }
    },
    {
        "id": "zz24",
        "colour": "#973f54",
        "fg": "#fff",
        "name": {
            "en": "Line 24",
            "zh-Hans": "24号线",
            "zh-Hant": "24號線"
        }
    },
    {
        "id": "zz25",
        "colour": "#a1c6e2",
        "fg": "#fff",
        "name": {
            "en": "Line 25",
            "zh-Hans": "25号线",
            "zh-Hant": "25號線"
        }
    },
    {
        "id": "zz26",
        "colour": "#4d9c87",
        "fg": "#fff",
        "name": {
            "en": "Line 26",
            "zh-Hans": "26号线",
            "zh-Hant": "26號線"
        }
    }
]</details>

**Comment by 52PD** [comment] 2023-07-19 03:10
Closed as duplicate of #693 .

**Closed by 52PD** 2023-07-19 03:10 UTC
Labels: duplicate, resources
